// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3asoft.Masterminds.Data;

namespace _3asoft.Masterminds.Data.Migrations
{
    [DbContext(typeof(MastermindsDbContext))]
    [Migration("20220105132737_InitMentorsDb100")]
    partial class InitMentorsDb100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_3asoft.Masterminds.Core.Entities.MentorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desctiption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Mentors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desctiption = "Beatae dolorem optio unde voluptatibus iste aut repudiandae nihil.\nAsperiores et suscipit eaque.\nVoluptate nesciunt omnis animi voluptatem expedita necessitatibus sint facere nostrum.",
                            Name = "Sophia Grant",
                            Profession = "vel",
                            Rate = 74.867143078459023,
                            Rating = 8.2505962803264126
                        },
                        new
                        {
                            Id = 2,
                            Desctiption = "Ut enim magnam aliquid ut incidunt laudantium ipsum nulla.\nReprehenderit delectus odio cupiditate tempora modi doloribus debitis eius.\nTempora velit dolor consectetur et rerum quaerat saepe fugit.\nEt est ducimus voluptatem.",
                            Name = "Astrid Kihn",
                            Profession = "cumque",
                            Rate = 59.156156037913703,
                            Rating = 0.15321737162453
                        },
                        new
                        {
                            Id = 3,
                            Desctiption = "Molestiae rem voluptas dolores tenetur.\nAssumenda eos eius impedit sed.\nEarum et aperiam sunt veritatis dignissimos ea aut sunt.\nNam ipsam nihil.\nNostrum saepe neque iusto odio illum exercitationem.",
                            Name = "Lon Bergstrom",
                            Profession = "temporibus",
                            Rate = 73.687914138328239,
                            Rating = 0.60355353662909639
                        },
                        new
                        {
                            Id = 4,
                            Desctiption = "Quos doloremque saepe rem delectus saepe molestias provident.\nAut qui aut expedita hic est quis.\nNon autem iusto voluptatem debitis cumque repellendus enim porro.\nIusto qui nemo possimus consequatur quos.\nAtque ut neque consectetur aliquid consequatur consequatur possimus exercitationem.",
                            Name = "Joanny Schmeler",
                            Profession = "est",
                            Rate = 50.985772560623374,
                            Rating = 6.9323761886602151
                        },
                        new
                        {
                            Id = 5,
                            Desctiption = "Sint aut ut sint est et.\nOdit velit dolore qui quasi.\nNostrum eius ea et rerum totam sit quia.\nDolor voluptatibus molestiae voluptatem culpa excepturi beatae.",
                            Name = "Cierra Quigley",
                            Profession = "voluptas",
                            Rate = 32.870985231115938,
                            Rating = 3.4549854525620982
                        },
                        new
                        {
                            Id = 6,
                            Desctiption = "Totam reiciendis neque accusamus non illo asperiores aut velit itaque.\nConsequatur ut ut.",
                            Name = "Twila Luettgen",
                            Profession = "sequi",
                            Rate = 84.386889510781913,
                            Rating = 3.9286034246574171
                        },
                        new
                        {
                            Id = 7,
                            Desctiption = "Sint dicta nisi aperiam illum doloremque aliquam eligendi.\nEsse voluptatem eveniet ut.",
                            Name = "Mia Goodwin",
                            Profession = "debitis",
                            Rate = 77.97120998761207,
                            Rating = 2.2059548283954871
                        },
                        new
                        {
                            Id = 8,
                            Desctiption = "Beatae similique quos numquam in ut minus.",
                            Name = "Skye Nienow",
                            Profession = "est",
                            Rate = 78.212951950548657,
                            Rating = 9.7491813123920839
                        },
                        new
                        {
                            Id = 9,
                            Desctiption = "Omnis necessitatibus illum fugiat reprehenderit.",
                            Name = "Daphnee Grady",
                            Profession = "ad",
                            Rate = 22.615679523169845,
                            Rating = 1.72264859626193
                        },
                        new
                        {
                            Id = 10,
                            Desctiption = "Nihil qui architecto.\nVeniam dolorum quasi cum omnis ut deserunt.\nPraesentium ad ullam accusantium.\nDelectus aliquid ratione consequatur rerum nisi.",
                            Name = "Alda Rippin",
                            Profession = "voluptate",
                            Rate = 33.999831466842366,
                            Rating = 5.2243757551649477
                        },
                        new
                        {
                            Id = 11,
                            Desctiption = "In ut corrupti totam quo minima sequi minus.\nOdio aut velit assumenda sed exercitationem est autem fugit qui.\nRepellat sed ipsum culpa exercitationem possimus aut voluptas.\nOccaecati eaque rerum temporibus rerum rerum fuga rerum.\nIusto sit officiis cum aut voluptates ipsa in quia eos.",
                            Name = "Ned Upton",
                            Profession = "omnis",
                            Rate = 76.730298630115712,
                            Rating = 1.2552158074710593
                        },
                        new
                        {
                            Id = 12,
                            Desctiption = "Adipisci et et quia vitae dolorem dolorem sunt.",
                            Name = "Isom Erdman",
                            Profession = "eum",
                            Rate = 64.709810139289971,
                            Rating = 3.9825325384654722
                        },
                        new
                        {
                            Id = 13,
                            Desctiption = "Quae iure cum impedit quo voluptatem incidunt quaerat.\nEveniet qui ut debitis nihil dolores similique.",
                            Name = "Jaqueline Jakubowski",
                            Profession = "nesciunt",
                            Rate = 80.609106701057911,
                            Rating = 8.863845862850475
                        },
                        new
                        {
                            Id = 14,
                            Desctiption = "Ex pariatur quae officia et molestias rerum omnis quis.\nOmnis ipsum repellat temporibus est laboriosam ut delectus ut quis.\nEt adipisci rerum libero laboriosam.\nLaborum consequatur tempore quas pariatur ipsam sunt quia vero.",
                            Name = "Karlie Morar",
                            Profession = "numquam",
                            Rate = 94.30176105932415,
                            Rating = 8.2429463920383466
                        },
                        new
                        {
                            Id = 15,
                            Desctiption = "Sunt aut magnam eos dolor.",
                            Name = "Patience Reynolds",
                            Profession = "qui",
                            Rate = 94.329832901586698,
                            Rating = 6.5150077624782021
                        },
                        new
                        {
                            Id = 16,
                            Desctiption = "Vero expedita aut sint neque tempore enim.\nEt autem non vero molestiae totam fugiat omnis et.",
                            Name = "Rudy Goodwin",
                            Profession = "et",
                            Rate = 97.852311830712623,
                            Rating = 2.8337761819519924
                        },
                        new
                        {
                            Id = 17,
                            Desctiption = "Quam sed illo possimus minus aut porro error tenetur.",
                            Name = "Davin Schaefer",
                            Profession = "quisquam",
                            Rate = 32.522743463852791,
                            Rating = 2.0521878274400662
                        },
                        new
                        {
                            Id = 18,
                            Desctiption = "Vel ut cum.\nQuia qui quo ipsam voluptatem est dolore unde.\nFacilis eum et unde aliquam et.",
                            Name = "Alexandre Kohler",
                            Profession = "sed",
                            Rate = 87.634751957019219,
                            Rating = 8.1523135575243799
                        },
                        new
                        {
                            Id = 19,
                            Desctiption = "Ut qui alias harum eos.\nTempore impedit laboriosam consequatur non reprehenderit tempore voluptatem quos.\nId consequatur iste ipsum quasi enim est vel.\nEt ipsam id laudantium et nemo et illo.",
                            Name = "Vickie Mosciski",
                            Profession = "sint",
                            Rate = 20.418565628034326,
                            Rating = 8.1001967555378549
                        },
                        new
                        {
                            Id = 20,
                            Desctiption = "Debitis temporibus corporis sunt quia sequi.\nVoluptatum totam debitis omnis aperiam magnam corrupti.\nDeserunt maxime consectetur voluptatibus et.\nEt et voluptatum quas nam laboriosam.\nProvident quia molestiae ut ratione aut nostrum veniam consequatur.",
                            Name = "Ramiro Kulas",
                            Profession = "ipsam",
                            Rate = 48.511725213616955,
                            Rating = 3.8793274312649517
                        },
                        new
                        {
                            Id = 21,
                            Desctiption = "Dicta enim laborum error sint ut similique.",
                            Name = "Ardella Pfeffer",
                            Profession = "dolores",
                            Rate = 104.23044543584363,
                            Rating = 8.3892260670611751
                        },
                        new
                        {
                            Id = 22,
                            Desctiption = "Et praesentium illum quisquam rerum exercitationem ducimus molestiae rerum.\nAdipisci aut qui tempore.\nAtque culpa est non expedita reprehenderit incidunt.",
                            Name = "Blanca Jaskolski",
                            Profession = "et",
                            Rate = 116.08647760957781,
                            Rating = 8.0942175621605568
                        },
                        new
                        {
                            Id = 23,
                            Desctiption = "Quo ratione atque id sit aut tempora soluta consequuntur saepe.\nEos expedita eum rem consequatur molestias ipsam eveniet et.",
                            Name = "Amalia Ryan",
                            Profession = "nisi",
                            Rate = 81.732167498828929,
                            Rating = 6.0591585450149879
                        },
                        new
                        {
                            Id = 24,
                            Desctiption = "Velit ipsa vel ipsam est eos corrupti quia asperiores.\nAd ea distinctio minima et blanditiis facere dicta.\nMinus nulla in voluptate quo ipsam impedit.",
                            Name = "Tia Stanton",
                            Profession = "ipsam",
                            Rate = 107.45906696154692,
                            Rating = 8.8873605378378926
                        },
                        new
                        {
                            Id = 25,
                            Desctiption = "Quia vel quidem maxime culpa sequi repellat dolorem.\nDeleniti expedita incidunt voluptates.\nLaboriosam quia reprehenderit error.\nQuis cumque doloribus quo quidem ut repellat voluptatibus ducimus.\nNemo neque aut molestiae distinctio corrupti.",
                            Name = "Mathilde Armstrong",
                            Profession = "et",
                            Rate = 102.60324558746221,
                            Rating = 6.043750003931927
                        },
                        new
                        {
                            Id = 26,
                            Desctiption = "Quidem explicabo facere id voluptate rem ex.\nRem enim vel voluptatum quae amet reiciendis alias quia culpa.\nOmnis optio ut voluptatem.",
                            Name = "Jalon Cummerata",
                            Profession = "impedit",
                            Rate = 34.266836004549091,
                            Rating = 9.3197153039834078
                        },
                        new
                        {
                            Id = 27,
                            Desctiption = "Iure eos pariatur dolores ex quod rerum recusandae.\nMolestias explicabo culpa quo necessitatibus exercitationem hic.\nCorporis corrupti neque quas deserunt possimus ut.\nMinus omnis quia et sequi est deleniti recusandae temporibus.\nTenetur et voluptates eum ut fugit enim doloribus nam blanditiis.",
                            Name = "Karlie Schneider",
                            Profession = "magnam",
                            Rate = 93.700296599185222,
                            Rating = 8.7552620697558208
                        },
                        new
                        {
                            Id = 28,
                            Desctiption = "Iure autem dolor quibusdam aut aut.\nDolorum delectus soluta dolores iusto.\nEt facilis ab aut nisi voluptatem nihil rem aliquam.\nUt animi sunt.",
                            Name = "Betty Bergstrom",
                            Profession = "molestiae",
                            Rate = 42.09671141723949,
                            Rating = 8.5650483325892353
                        },
                        new
                        {
                            Id = 29,
                            Desctiption = "Veniam sunt qui est dicta pariatur maxime.\nNon ut iusto eos iste aut voluptas rem.\nQuam et sed.\nUt dolores maxime rerum adipisci perferendis consequatur molestias a et.\nConsectetur repudiandae et cupiditate quas odio molestiae dolores.",
                            Name = "Johnpaul Roob",
                            Profession = "nam",
                            Rate = 52.395810183228832,
                            Rating = 9.5622795911330165
                        },
                        new
                        {
                            Id = 30,
                            Desctiption = "Quia libero veniam.",
                            Name = "Kiley Beer",
                            Profession = "voluptatem",
                            Rate = 118.42547923402184,
                            Rating = 6.117612284662953
                        },
                        new
                        {
                            Id = 31,
                            Desctiption = "Qui nam necessitatibus quo vel eos aliquam et quo rerum.\nEum ipsam ut in dolores velit sapiente officiis.",
                            Name = "Lyric Waters",
                            Profession = "ab",
                            Rate = 58.650823725317991,
                            Rating = 5.8793920725022408
                        },
                        new
                        {
                            Id = 32,
                            Desctiption = "Modi nemo nobis tempore dolor voluptas amet sunt.\nEst aperiam expedita.\nSint aut sit eveniet.\nEa dolorem aliquid ipsam.\nIusto rerum ducimus.",
                            Name = "Mckenzie Cormier",
                            Profession = "dolores",
                            Rate = 104.34286480953118,
                            Rating = 1.5069116239933815
                        },
                        new
                        {
                            Id = 33,
                            Desctiption = "Cum sint rerum.\nIpsa dolorem ipsam adipisci maxime et aut praesentium facere voluptas.\nEligendi illum ut cumque placeat reiciendis ut voluptates ut magnam.\nSit laborum in.",
                            Name = "Micaela Monahan",
                            Profession = "aut",
                            Rate = 43.484396705722617,
                            Rating = 8.1579202730944012
                        },
                        new
                        {
                            Id = 34,
                            Desctiption = "Et consequatur vero voluptatibus sunt et est ducimus ut reiciendis.\nNobis possimus sint doloribus accusantium fugit asperiores illo sit consequatur.\nQuo aut fugiat cumque dolorum voluptatibus voluptatem nulla.",
                            Name = "Novella Spinka",
                            Profession = "a",
                            Rate = 46.809627113402641,
                            Rating = 6.257942037777017
                        },
                        new
                        {
                            Id = 35,
                            Desctiption = "Quisquam expedita ut quod praesentium ut.\nRatione est vero distinctio omnis.\nVoluptas corporis sunt amet asperiores ex et pariatur ratione.",
                            Name = "Casper Champlin",
                            Profession = "dolore",
                            Rate = 115.61583453026407,
                            Rating = 6.2923934572806548
                        },
                        new
                        {
                            Id = 36,
                            Desctiption = "Odio quibusdam quis ut est qui suscipit nihil deserunt.\nQuod odio eos amet voluptas a sed.\nAlias eos iste inventore.\nAd quibusdam non sunt ut suscipit fugit doloremque unde laudantium.\nNon inventore autem labore dolorem ducimus.",
                            Name = "Gina Anderson",
                            Profession = "fuga",
                            Rate = 60.630611681859293,
                            Rating = 4.2026060792629636
                        },
                        new
                        {
                            Id = 37,
                            Desctiption = "Sapiente unde illo nihil modi esse hic sed vel fugiat.\nMaxime quia qui.",
                            Name = "Viviane Strosin",
                            Profession = "mollitia",
                            Rate = 62.32813930880657,
                            Rating = 6.1183647979602052
                        },
                        new
                        {
                            Id = 38,
                            Desctiption = "Aut repellendus qui delectus ipsa iste.\nNobis laudantium occaecati nam qui ut laborum quisquam veniam est.\nMagni excepturi sit fugiat tempora commodi dolores ipsa fuga.\nQuas sed non quam ut sint maiores voluptas rem praesentium.\nEos illo occaecati sint.",
                            Name = "Annamarie Hilll",
                            Profession = "deleniti",
                            Rate = 69.730343671017479,
                            Rating = 1.9293415415703046
                        },
                        new
                        {
                            Id = 39,
                            Desctiption = "Temporibus nihil veritatis.\nQuis qui iste modi totam repellat.",
                            Name = "Elvie Heidenreich",
                            Profession = "nesciunt",
                            Rate = 76.50249424944748,
                            Rating = 2.0978693208181625
                        },
                        new
                        {
                            Id = 40,
                            Desctiption = "Accusantium fuga tenetur vel incidunt.\nEnim praesentium nam repudiandae repudiandae perferendis suscipit laudantium.",
                            Name = "Toby Ziemann",
                            Profession = "sit",
                            Rate = 51.987208026734749,
                            Rating = 5.9263773755758899
                        },
                        new
                        {
                            Id = 41,
                            Desctiption = "Tempora voluptas quia magnam doloribus sit non veritatis suscipit.\nPorro aut vel iste qui reprehenderit enim.",
                            Name = "Hattie Lueilwitz",
                            Profession = "quam",
                            Rate = 50.395221031641228,
                            Rating = 2.232122860025672
                        },
                        new
                        {
                            Id = 42,
                            Desctiption = "Quia dolores provident excepturi odio omnis perferendis consequatur.\nIn quibusdam dolor placeat error et dignissimos laboriosam in voluptas.",
                            Name = "Keagan Blanda",
                            Profession = "temporibus",
                            Rate = 16.715782961675796,
                            Rating = 6.2382566073156216
                        },
                        new
                        {
                            Id = 43,
                            Desctiption = "Voluptatem est ratione similique.\nAnimi et error ipsa at est quam dolorum in.\nUt numquam ut possimus et facilis impedit.\nEt qui id exercitationem rerum.\nNostrum laborum fuga soluta veniam laborum.",
                            Name = "Eve Dietrich",
                            Profession = "repudiandae",
                            Rate = 70.409198133651728,
                            Rating = 9.0748685128404141
                        },
                        new
                        {
                            Id = 44,
                            Desctiption = "Occaecati iure quibusdam et.",
                            Name = "Dedrick Fadel",
                            Profession = "voluptatem",
                            Rate = 100.58800730462559,
                            Rating = 1.9678691504373538
                        },
                        new
                        {
                            Id = 45,
                            Desctiption = "Doloremque sint dignissimos blanditiis.\nFugit nesciunt nemo qui sed facere labore.",
                            Name = "Orville Rolfson",
                            Profession = "repellendus",
                            Rate = 104.08572253113879,
                            Rating = 6.9768148972544886
                        },
                        new
                        {
                            Id = 46,
                            Desctiption = "Quam natus harum laudantium amet non fugiat provident dolorem perspiciatis.",
                            Name = "Alberta Rippin",
                            Profession = "suscipit",
                            Rate = 116.10490407455011,
                            Rating = 3.1352809179272878
                        },
                        new
                        {
                            Id = 47,
                            Desctiption = "Ipsum temporibus nihil sed et necessitatibus odio veritatis assumenda.\nEst sit dignissimos temporibus.\nQuisquam et accusamus deserunt qui illo.\nNon soluta qui sit omnis.",
                            Name = "Bart Miller",
                            Profession = "mollitia",
                            Rate = 49.89709817333943,
                            Rating = 4.7527763642150802
                        },
                        new
                        {
                            Id = 48,
                            Desctiption = "Autem cupiditate quam eligendi voluptas libero adipisci.",
                            Name = "Linwood Leannon",
                            Profession = "nesciunt",
                            Rate = 111.2897420621895,
                            Rating = 5.4858123955716431
                        },
                        new
                        {
                            Id = 49,
                            Desctiption = "Harum aut autem blanditiis rerum aliquam porro sint voluptatem.\nDolorum voluptatem consequuntur.",
                            Name = "Grant Johnston",
                            Profession = "dolor",
                            Rate = 22.781336690942446,
                            Rating = 3.4671770704291656
                        },
                        new
                        {
                            Id = 50,
                            Desctiption = "Repellat rerum ullam aut aut et sed et fugiat.",
                            Name = "Rasheed Little",
                            Profession = "laborum",
                            Rate = 40.122597581670902,
                            Rating = 2.2300493960408723
                        },
                        new
                        {
                            Id = 51,
                            Desctiption = "Commodi praesentium nam eum at officiis voluptatem in.\nDignissimos ut vel.\nConsequatur omnis voluptas dolore molestias possimus nobis culpa soluta.\nSapiente ab veritatis vitae sint.\nVel quis sed qui et dolore.",
                            Name = "Natalia Mosciski",
                            Profession = "labore",
                            Rate = 114.79356957226692,
                            Rating = 0.094358632384966418
                        },
                        new
                        {
                            Id = 52,
                            Desctiption = "Eaque expedita vel dolorem et voluptatem consectetur omnis doloribus odio.\nEnim inventore soluta aut cumque.\nAutem autem maxime asperiores eligendi architecto nihil natus hic.\nDolor veniam voluptatibus corrupti harum alias soluta.",
                            Name = "Ole Macejkovic",
                            Profession = "ut",
                            Rate = 18.338488078740653,
                            Rating = 1.2312769010808677
                        },
                        new
                        {
                            Id = 53,
                            Desctiption = "Et reprehenderit non et excepturi.",
                            Name = "Lula Price",
                            Profession = "culpa",
                            Rate = 39.632138581030134,
                            Rating = 2.608048288434766
                        },
                        new
                        {
                            Id = 54,
                            Desctiption = "Itaque et ut culpa a.\nPariatur praesentium velit dolores aut.",
                            Name = "Roselyn Mann",
                            Profession = "libero",
                            Rate = 105.02695228207249,
                            Rating = 4.8749324096715698
                        },
                        new
                        {
                            Id = 55,
                            Desctiption = "Iste provident minus.\nCommodi ullam qui natus quae aut.\nFugit molestiae quos quaerat ullam et est ullam sed fuga.",
                            Name = "Vella Mueller",
                            Profession = "nemo",
                            Rate = 55.159320112112596,
                            Rating = 0.36477842850833131
                        },
                        new
                        {
                            Id = 56,
                            Desctiption = "Et sed rem non voluptatem minus recusandae optio mollitia sint.\nQuae iusto in eius placeat praesentium exercitationem.",
                            Name = "Veronica Jenkins",
                            Profession = "animi",
                            Rate = 111.20014266995719,
                            Rating = 1.3134994363940784
                        },
                        new
                        {
                            Id = 57,
                            Desctiption = "Quis dolores mollitia quia dolores quas ut et.\nVoluptatem nulla harum rem.\nEligendi natus error nihil omnis ut aliquam soluta tempora.\nDistinctio eos et veritatis et veniam et sapiente.",
                            Name = "Ansley Larson",
                            Profession = "eligendi",
                            Rate = 49.558907077721742,
                            Rating = 2.4011209385474777
                        },
                        new
                        {
                            Id = 58,
                            Desctiption = "Aut nemo quia enim beatae autem.\nDoloribus ducimus vel.\nMagni dolorum est consequatur deleniti id enim vero praesentium repellat.",
                            Name = "Saul Schiller",
                            Profession = "reiciendis",
                            Rate = 40.868904577227724,
                            Rating = 3.3743458862296984
                        },
                        new
                        {
                            Id = 59,
                            Desctiption = "Soluta officiis blanditiis modi doloribus labore ut molestiae magni.\nRatione consequatur perspiciatis ratione ipsum nobis.\nSequi corporis ad quas enim quis delectus deleniti fugit totam.\nDolores et eum.\nQuos ea enim sunt molestiae id eos vel.",
                            Name = "Shemar D'Amore",
                            Profession = "inventore",
                            Rate = 108.07389559823736,
                            Rating = 3.978455012654166
                        },
                        new
                        {
                            Id = 60,
                            Desctiption = "Pariatur quo corrupti voluptatem qui explicabo est aliquam quis quas.\nQuod debitis est esse temporibus veritatis.\nLaudantium officiis amet.",
                            Name = "Callie Kiehn",
                            Profession = "aliquid",
                            Rate = 36.263908158179333,
                            Rating = 1.231068573534055
                        },
                        new
                        {
                            Id = 61,
                            Desctiption = "Veritatis a dolor.\nAsperiores velit et velit facilis sint et qui rerum.\nEarum quasi iusto.\nQuaerat est minus et quis dolorem expedita et qui sit.\nQui reiciendis quo.",
                            Name = "Robert Mills",
                            Profession = "omnis",
                            Rate = 33.946601551466898,
                            Rating = 0.17154252630264616
                        },
                        new
                        {
                            Id = 62,
                            Desctiption = "Soluta sequi consequatur qui ratione autem aut doloribus.\nSaepe provident quia.\nPossimus ipsam reprehenderit velit.\nPerferendis amet autem totam animi exercitationem sint itaque.",
                            Name = "Chance Kub",
                            Profession = "consectetur",
                            Rate = 58.88267336417114,
                            Rating = 3.2333260696536517
                        },
                        new
                        {
                            Id = 63,
                            Desctiption = "Dolore culpa blanditiis qui molestias qui autem omnis et.\nQuia qui voluptate aut tenetur eos sunt dolor.\nEnim blanditiis quis non omnis impedit tempora quia.\nTotam officia ipsum ea repellendus non.",
                            Name = "Trinity Jenkins",
                            Profession = "ea",
                            Rate = 110.84102842846933,
                            Rating = 5.3124307819234353
                        },
                        new
                        {
                            Id = 64,
                            Desctiption = "Voluptate placeat dolorem voluptatum.\nMolestias dolores maiores omnis enim magni temporibus iusto.\nOfficiis consequatur ut voluptatem veniam.",
                            Name = "Toby Daugherty",
                            Profession = "vero",
                            Rate = 84.918379187545924,
                            Rating = 9.0378196905543184
                        },
                        new
                        {
                            Id = 65,
                            Desctiption = "Aut officiis omnis alias et debitis non sunt quae.\nIure beatae asperiores porro architecto qui sint.\nEaque similique ut amet illo.\nA rerum dolorum mollitia et aspernatur impedit ut quo.",
                            Name = "Trace Hermiston",
                            Profession = "enim",
                            Rate = 20.278002053628676,
                            Rating = 4.749151633469924
                        },
                        new
                        {
                            Id = 66,
                            Desctiption = "In ut nostrum magnam voluptatibus.\nAccusantium error eos et reprehenderit omnis iusto adipisci qui.\nIllum ut quae temporibus aliquam et tempora hic.\nEaque commodi beatae dicta vel et quis in repellendus asperiores.\nSaepe et dolorem.",
                            Name = "Taurean Murphy",
                            Profession = "quaerat",
                            Rate = 37.653273400223469,
                            Rating = 5.4819696096153789
                        },
                        new
                        {
                            Id = 67,
                            Desctiption = "Repudiandae occaecati laudantium itaque odio labore quas sunt alias sapiente.\nNisi laboriosam earum.\nRerum voluptatum quae nam voluptatem commodi.\nSed qui quibusdam sit qui repudiandae quia adipisci.",
                            Name = "Brendon Morar",
                            Profession = "inventore",
                            Rate = 92.435110792440881,
                            Rating = 9.5726569041482428
                        },
                        new
                        {
                            Id = 68,
                            Desctiption = "Voluptatem quis consequatur et nemo dolor aperiam.\nOmnis praesentium aut libero libero culpa est exercitationem nobis qui.\nIpsam perferendis eos nihil aspernatur.\nSint aut architecto at aut vel illum.\nVoluptas voluptas cum expedita sequi inventore accusamus.",
                            Name = "Shaun Gleichner",
                            Profession = "et",
                            Rate = 116.13704751792227,
                            Rating = 1.2548244983213137
                        },
                        new
                        {
                            Id = 69,
                            Desctiption = "Et adipisci aut iste vel et non.\nPerferendis hic voluptates ad reprehenderit reiciendis a.",
                            Name = "Ceasar Marquardt",
                            Profession = "dolore",
                            Rate = 74.048291293461006,
                            Rating = 2.5812695140863164
                        },
                        new
                        {
                            Id = 70,
                            Desctiption = "Perferendis quidem non non qui.\nOdio necessitatibus et quo.",
                            Name = "Albin Kirlin",
                            Profession = "vitae",
                            Rate = 22.931513112751539,
                            Rating = 0.53530470493030957
                        },
                        new
                        {
                            Id = 71,
                            Desctiption = "Tenetur sunt est.\nQui placeat debitis libero necessitatibus.\nUnde quibusdam voluptatum adipisci.",
                            Name = "Fabian Jenkins",
                            Profession = "amet",
                            Rate = 107.58006344650876,
                            Rating = 8.803822397628716
                        },
                        new
                        {
                            Id = 72,
                            Desctiption = "Totam vel neque quia vitae quasi non reiciendis temporibus.",
                            Name = "Clarabelle Cummerata",
                            Profession = "commodi",
                            Rate = 35.224148425191707,
                            Rating = 3.3717868306542687
                        },
                        new
                        {
                            Id = 73,
                            Desctiption = "Earum quis rerum est eos quas recusandae.\nSunt reprehenderit facilis nesciunt et dolorem optio perspiciatis sint voluptatem.\nImpedit natus amet facilis soluta hic.\nAspernatur eos ea necessitatibus qui vitae modi omnis.\nEveniet qui vel maiores delectus ducimus.",
                            Name = "Archibald Considine",
                            Profession = "et",
                            Rate = 24.578867376958421,
                            Rating = 1.1010754579217523
                        },
                        new
                        {
                            Id = 74,
                            Desctiption = "Vel animi reprehenderit non fuga quaerat illo facere rerum quia.\nQuia ea quibusdam quos velit repellat error recusandae.\nEa et explicabo dolores dolorem occaecati quaerat nostrum.\nTenetur quaerat quia tenetur.",
                            Name = "Donato Bartoletti",
                            Profession = "est",
                            Rate = 60.099931192072077,
                            Rating = 7.7393222543128406
                        },
                        new
                        {
                            Id = 75,
                            Desctiption = "Dolores libero quaerat dolore cum vel natus et dolor eum.\nEos voluptas ipsa natus culpa molestias aliquam voluptas.\nRepellat voluptas mollitia.",
                            Name = "Brianne Rowe",
                            Profession = "et",
                            Rate = 68.071545556966001,
                            Rating = 4.661610622267057
                        },
                        new
                        {
                            Id = 76,
                            Desctiption = "Cumque non odit delectus adipisci minus ut pariatur.",
                            Name = "Marlen White",
                            Profession = "non",
                            Rate = 38.962043165025321,
                            Rating = 2.6939935855073829
                        },
                        new
                        {
                            Id = 77,
                            Desctiption = "In sit repudiandae sunt dolor.\nEt cumque aliquid ut minus.",
                            Name = "Jaeden Herman",
                            Profession = "a",
                            Rate = 79.478158251605066,
                            Rating = 5.0999571639578587
                        },
                        new
                        {
                            Id = 78,
                            Desctiption = "Sunt magni neque possimus debitis nulla eum.\nDistinctio quibusdam velit.",
                            Name = "Archibald Marquardt",
                            Profession = "ullam",
                            Rate = 31.521197744142817,
                            Rating = 5.9445776678363691
                        },
                        new
                        {
                            Id = 79,
                            Desctiption = "Nemo optio vero in.\nEum facere asperiores laudantium expedita ut.\nEnim possimus libero asperiores quam adipisci aspernatur.",
                            Name = "Cade Howe",
                            Profession = "aliquam",
                            Rate = 44.156360729297788,
                            Rating = 4.2386516855278291
                        },
                        new
                        {
                            Id = 80,
                            Desctiption = "Nostrum quia qui voluptatum aut voluptatem.\nHic quis mollitia omnis eligendi tempore suscipit consequatur.\nEum quia quasi aut atque expedita deleniti reprehenderit fugiat architecto.\nEt quod labore tenetur quo.",
                            Name = "Lucius Kling",
                            Profession = "et",
                            Rate = 93.339890104317988,
                            Rating = 1.4311463625315326
                        },
                        new
                        {
                            Id = 81,
                            Desctiption = "Qui et ea totam architecto ut qui cupiditate omnis.\nSimilique soluta similique architecto occaecati delectus harum qui.\nFacilis minus qui voluptas.\nQuae rerum quae molestiae.\nQuibusdam praesentium voluptatum in quia dolore enim quia.",
                            Name = "Obie Altenwerth",
                            Profession = "ut",
                            Rate = 72.717357268518469,
                            Rating = 4.0804905370252627
                        },
                        new
                        {
                            Id = 82,
                            Desctiption = "Quia iste eum quidem dolore.\nEt illum numquam.\nSed repellat sapiente voluptatem quam.",
                            Name = "Cierra Jaskolski",
                            Profession = "nesciunt",
                            Rate = 27.003640597501601,
                            Rating = 5.5171242056028564
                        },
                        new
                        {
                            Id = 83,
                            Desctiption = "Veniam dolore dolorem.",
                            Name = "Hilton Dibbert",
                            Profession = "aut",
                            Rate = 105.24596958143916,
                            Rating = 9.6161377428174646
                        },
                        new
                        {
                            Id = 84,
                            Desctiption = "Aliquam sunt aperiam quos.\nVoluptate cum dolorum saepe facilis.\nIllo quia magnam ut ut.",
                            Name = "Corrine Spinka",
                            Profession = "dignissimos",
                            Rate = 49.586765808140285,
                            Rating = 0.35400193201098684
                        },
                        new
                        {
                            Id = 85,
                            Desctiption = "Beatae enim dolores.\nEaque sed praesentium dolores dolor aut itaque maxime reprehenderit.\nNon ipsum omnis.\nLabore quasi sed eum.",
                            Name = "Nyasia Wolf",
                            Profession = "ut",
                            Rate = 47.114394257829701,
                            Rating = 6.9385144193370429
                        },
                        new
                        {
                            Id = 86,
                            Desctiption = "Et et corrupti est deleniti.\nEius quia mollitia rerum esse et voluptatem vitae magnam ut.\nA at quo aut consectetur dolorem blanditiis.\nIste magnam ipsa explicabo ut quia sit.",
                            Name = "Daphnee Bauch",
                            Profession = "in",
                            Rate = 105.66669890874377,
                            Rating = 8.71804869208394
                        },
                        new
                        {
                            Id = 87,
                            Desctiption = "Neque quo ab sit corrupti qui quidem iure placeat reiciendis.",
                            Name = "Osvaldo Cormier",
                            Profession = "fugit",
                            Rate = 74.62860750864661,
                            Rating = 4.5054585973291932
                        },
                        new
                        {
                            Id = 88,
                            Desctiption = "Architecto doloremque aut et nihil quia accusantium ea laudantium dicta.\nRepellat delectus est illum velit ab eligendi quia.\nAut cum harum ut ipsum et et voluptatem dolorem.",
                            Name = "Omer Bernhard",
                            Profession = "ut",
                            Rate = 18.114293548797392,
                            Rating = 8.4238513505197368
                        },
                        new
                        {
                            Id = 89,
                            Desctiption = "Voluptatibus doloribus blanditiis ut voluptatem qui.\nId voluptatibus iure.\nNostrum a expedita at voluptas quisquam repellendus et qui.",
                            Name = "Donna Hahn",
                            Profession = "itaque",
                            Rate = 79.308922216253777,
                            Rating = 2.3849374765460087
                        },
                        new
                        {
                            Id = 90,
                            Desctiption = "Adipisci est quo reprehenderit.\nVelit in molestiae veritatis labore qui minus amet.\nEveniet sint repellendus porro omnis commodi excepturi esse.\nEius qui quis explicabo voluptatem est labore dolore et ipsam.",
                            Name = "Grace Ebert",
                            Profession = "placeat",
                            Rate = 37.69095088787887,
                            Rating = 1.0847517387404813
                        },
                        new
                        {
                            Id = 91,
                            Desctiption = "Natus tempora autem.",
                            Name = "Lola Sipes",
                            Profession = "sapiente",
                            Rate = 44.22154588560646,
                            Rating = 9.9431483307588611
                        },
                        new
                        {
                            Id = 92,
                            Desctiption = "Delectus quos sit nisi soluta.\nTemporibus quos similique ex aut autem et qui doloribus.\nEsse iste qui itaque.",
                            Name = "Ashtyn Collier",
                            Profession = "illo",
                            Rate = 86.721312154885993,
                            Rating = 7.4024585110146823
                        },
                        new
                        {
                            Id = 93,
                            Desctiption = "Eveniet dicta assumenda eligendi ex cupiditate atque.\nPossimus aspernatur aut hic illo.",
                            Name = "Lyla Schiller",
                            Profession = "nam",
                            Rate = 87.315035130323395,
                            Rating = 8.0420183660658164
                        },
                        new
                        {
                            Id = 94,
                            Desctiption = "Ut aspernatur voluptatibus quidem quia sint natus.",
                            Name = "Chandler Sanford",
                            Profession = "nihil",
                            Rate = 88.465543902230237,
                            Rating = 9.8866563848623343
                        },
                        new
                        {
                            Id = 95,
                            Desctiption = "Necessitatibus voluptate et nam.\nPariatur ipsum omnis incidunt illo dignissimos est assumenda.",
                            Name = "Lucius Daniel",
                            Profession = "dolorem",
                            Rate = 83.380312099112345,
                            Rating = 5.3913750990253764
                        },
                        new
                        {
                            Id = 96,
                            Desctiption = "Et quibusdam aut magni sunt odio delectus voluptas.\nNon qui et.\nUt veniam consequatur dolorum doloremque et suscipit.\nQuam et molestiae adipisci sint voluptatem.",
                            Name = "Nora Swaniawski",
                            Profession = "consequatur",
                            Rate = 116.62341302140774,
                            Rating = 6.9645030689260468
                        },
                        new
                        {
                            Id = 97,
                            Desctiption = "Quas sunt nemo tempore explicabo nemo rerum voluptas.\nUllam id aut illo et deleniti.\nMaxime itaque blanditiis veniam corporis incidunt non.\nItaque inventore quis dolorem.\nExercitationem architecto et.",
                            Name = "Phoebe Runte",
                            Profession = "aut",
                            Rate = 105.35227841164557,
                            Rating = 9.5075886554585729
                        },
                        new
                        {
                            Id = 98,
                            Desctiption = "Recusandae qui beatae ut similique quia sit praesentium veniam voluptatem.\nInventore et dolores quidem eum.\nNeque magni id eaque voluptatem.\nAliquam nesciunt tempora aut et amet rem veniam.\nQuibusdam repellat occaecati fugiat tempora quaerat.",
                            Name = "Jonathan Streich",
                            Profession = "qui",
                            Rate = 36.244943620844253,
                            Rating = 0.61355167097111774
                        },
                        new
                        {
                            Id = 99,
                            Desctiption = "Ut voluptatem alias debitis deleniti quia doloremque recusandae non.\nRepudiandae id qui vel laboriosam eius nobis enim vel aperiam.\nQuaerat molestiae aut et nesciunt perferendis quibusdam enim voluptatibus.\nPerferendis et ducimus molestiae beatae aspernatur.\nNihil ut magnam excepturi officia aspernatur est.",
                            Name = "Frank Steuber",
                            Profession = "possimus",
                            Rate = 78.063283391326337,
                            Rating = 0.06031440108097829
                        },
                        new
                        {
                            Id = 100,
                            Desctiption = "Adipisci vel maiores aut tempora.",
                            Name = "Ayden Jaskolski",
                            Profession = "ducimus",
                            Rate = 18.76797978783398,
                            Rating = 6.3811550272540902
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
