// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3asoft.Masterminds.Data;

namespace _3asoft.Masterminds.Data.Migrations
{
    [DbContext(typeof(MastermindsDbContext))]
    [Migration("20220105114004_InitMentorsDb")]
    partial class InitMentorsDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_3asoft.Masterminds.Core.Entities.MentorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desctiption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Mentors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desctiption = "Fugit quam distinctio iusto eum quasi error et.\nEos corporis possimus reprehenderit at a vel mollitia.",
                            Name = "Isobel Heller",
                            Profession = "voluptatem",
                            Rate = 89.077817323560737,
                            Rating = 6.0077489847353425
                        },
                        new
                        {
                            Id = 2,
                            Desctiption = "Et quas asperiores.\nSaepe ipsam dolorum facere ea exercitationem expedita.",
                            Name = "Mallie Fay",
                            Profession = "inventore",
                            Rate = 32.522450598200059,
                            Rating = 0.98678347700591362
                        },
                        new
                        {
                            Id = 3,
                            Desctiption = "Distinctio assumenda et voluptatem et voluptate.\nSed omnis eaque quis quia deserunt.\nAb laborum alias.\nArchitecto a aliquid commodi et unde ex aspernatur adipisci ut.\nCumque animi sapiente inventore voluptas iusto animi sit velit.",
                            Name = "Mason Barrows",
                            Profession = "saepe",
                            Rate = 22.842262075488577,
                            Rating = 2.6811648591799497
                        },
                        new
                        {
                            Id = 4,
                            Desctiption = "Adipisci nihil rerum rerum esse necessitatibus.\nConsectetur ipsa eaque ullam.\nIpsam libero aut non modi placeat pariatur.",
                            Name = "Lavonne McGlynn",
                            Profession = "sed",
                            Rate = 53.220844531814024,
                            Rating = 7.604273537920915
                        },
                        new
                        {
                            Id = 5,
                            Desctiption = "Deserunt veniam corrupti voluptas asperiores id.\nDolorem nesciunt qui iste et consequatur vel esse.\nSit est eos beatae accusamus maxime autem autem eveniet.",
                            Name = "Hubert Jenkins",
                            Profession = "voluptatem",
                            Rate = 101.93472591337502,
                            Rating = 5.7943596857573656
                        },
                        new
                        {
                            Id = 6,
                            Desctiption = "Adipisci maiores ullam.\nCumque sed ipsa optio eos ratione molestias velit expedita deserunt.\nEaque sit rerum dolores aspernatur odio.\nNatus nulla corrupti fugit rerum.\nEligendi sint velit fugit sint quos.",
                            Name = "Lempi Vandervort",
                            Profession = "ratione",
                            Rate = 116.96739975380125,
                            Rating = 0.4504692370307023
                        },
                        new
                        {
                            Id = 7,
                            Desctiption = "Dignissimos numquam est ut vel porro corporis modi.\nConsequuntur voluptas voluptates omnis dolorum dolorem nihil qui velit.\nAliquam et alias ut hic qui saepe.\nNeque repellat cupiditate quas.\nVoluptatem quam repellat sequi quo est aut.",
                            Name = "Hollis Hoppe",
                            Profession = "sint",
                            Rate = 69.726499682444384,
                            Rating = 0.65886151541902749
                        },
                        new
                        {
                            Id = 8,
                            Desctiption = "Quod accusamus est sapiente.\nAut deleniti natus.\nDignissimos et est.\nAtque omnis eos tempora ut fuga facere deserunt ea.\nTempore qui nulla corporis amet laborum corrupti.",
                            Name = "Grayce Nitzsche",
                            Profession = "dolorem",
                            Rate = 101.55659976562326,
                            Rating = 3.8655549724891576
                        },
                        new
                        {
                            Id = 9,
                            Desctiption = "Aperiam praesentium in aspernatur omnis reprehenderit iste.\nVeritatis assumenda fuga pariatur quas.",
                            Name = "Chaya Windler",
                            Profession = "beatae",
                            Rate = 36.297899376460308,
                            Rating = 1.5561883996968104
                        },
                        new
                        {
                            Id = 10,
                            Desctiption = "Itaque vel numquam quibusdam.\nRerum ut voluptatem et optio.",
                            Name = "Tressie Kozey",
                            Profession = "omnis",
                            Rate = 28.344720273625441,
                            Rating = 6.0971789742341169
                        },
                        new
                        {
                            Id = 11,
                            Desctiption = "Et fugiat delectus et.\nOccaecati beatae soluta laboriosam aut omnis.\nVelit sapiente qui est quae dolorum expedita et.\nConsequatur illum at exercitationem eum consequatur sed.\nDeserunt sint maxime qui sed.",
                            Name = "Luther Harber",
                            Profession = "aliquam",
                            Rate = 76.898891463083629,
                            Rating = 1.9214949812374522
                        },
                        new
                        {
                            Id = 12,
                            Desctiption = "Sed hic fugiat maiores.\nNihil minus veritatis iste non delectus sed.\nDolorum nulla sit fugit est repellat voluptatem a.\nPlaceat adipisci aut sed nam et.\nEa eos et et odit corrupti vero voluptatibus et.",
                            Name = "Jalen Sanford",
                            Profession = "velit",
                            Rate = 35.20934669832203,
                            Rating = 5.530618399163064
                        },
                        new
                        {
                            Id = 13,
                            Desctiption = "Non earum repudiandae et omnis ullam velit iste impedit dolor.\nSed rerum sit odio eaque ut aliquam adipisci.",
                            Name = "Mya Parker",
                            Profession = "quidem",
                            Rate = 22.020022348696376,
                            Rating = 7.3922689060644569
                        },
                        new
                        {
                            Id = 14,
                            Desctiption = "Magnam aperiam voluptatem.\nUt est commodi labore mollitia quia placeat.\nQuae veritatis qui excepturi explicabo molestiae possimus expedita laboriosam nobis.\nRerum ea quibusdam perspiciatis eaque.\nVoluptatum voluptate dolor.",
                            Name = "Fabian Tromp",
                            Profession = "minus",
                            Rate = 71.829995028409172,
                            Rating = 1.3559988706167783
                        },
                        new
                        {
                            Id = 15,
                            Desctiption = "Vitae quo in officia voluptatem.",
                            Name = "Loma Reinger",
                            Profession = "quae",
                            Rate = 55.140214144690063,
                            Rating = 2.3717177297788288
                        },
                        new
                        {
                            Id = 16,
                            Desctiption = "Est vel sit eligendi similique quod cum fugit.\nAut voluptas amet.",
                            Name = "Elbert Herman",
                            Profession = "non",
                            Rate = 29.705850443945195,
                            Rating = 8.9469916601418475
                        },
                        new
                        {
                            Id = 17,
                            Desctiption = "Ad ut est.",
                            Name = "Bianka Runte",
                            Profession = "delectus",
                            Rate = 42.290450142738614,
                            Rating = 3.2104986827869424
                        },
                        new
                        {
                            Id = 18,
                            Desctiption = "Officia esse qui.\nQuo quibusdam in ullam doloremque deleniti quidem natus.",
                            Name = "Mariah Schumm",
                            Profession = "earum",
                            Rate = 26.099628855613815,
                            Rating = 0.33768000096905976
                        },
                        new
                        {
                            Id = 19,
                            Desctiption = "Quia aut necessitatibus fugit illum fugit.\nSapiente nihil excepturi facere rem nihil voluptas veritatis.\nNobis sit cupiditate veniam ut similique tenetur.",
                            Name = "Arjun Daniel",
                            Profession = "reiciendis",
                            Rate = 69.336752728063956,
                            Rating = 2.1218544720308179
                        },
                        new
                        {
                            Id = 20,
                            Desctiption = "Nemo qui fuga sed voluptatem hic optio corporis.\nUnde explicabo quo optio repellendus.\nConsequatur non ut sit distinctio.",
                            Name = "Effie Lind",
                            Profession = "odio",
                            Rate = 90.236872996965829,
                            Rating = 8.2204237199483554
                        },
                        new
                        {
                            Id = 21,
                            Desctiption = "Animi in vel in.\nCorrupti consequatur quia voluptatem nulla dolorem corporis fugit illum eum.\nAut amet magni accusamus dolorem aut provident molestias deleniti.\nVel ea reiciendis ipsa iusto aut ut et aspernatur.",
                            Name = "Elaina Hansen",
                            Profession = "est",
                            Rate = 35.795118847393951,
                            Rating = 5.2620052337935217
                        },
                        new
                        {
                            Id = 22,
                            Desctiption = "Aliquam nesciunt voluptas non ut nulla et.\nQuo alias qui necessitatibus voluptatibus officia.\nAccusamus et aut.\nAnimi incidunt voluptatibus velit sequi eaque enim porro.",
                            Name = "Mohamed West",
                            Profession = "voluptatem",
                            Rate = 34.709941688789954,
                            Rating = 3.4982758217948842
                        },
                        new
                        {
                            Id = 23,
                            Desctiption = "Possimus quis maxime unde ut ut dolores.",
                            Name = "Magdalena Volkman",
                            Profession = "dolorem",
                            Rate = 16.916119937280246,
                            Rating = 7.8251976509695869
                        },
                        new
                        {
                            Id = 24,
                            Desctiption = "Cum beatae tempora et cum sunt ut.\nPlaceat est saepe deserunt consequuntur.\nOmnis necessitatibus repellat laborum.\nQui fugiat cum quia quis non nihil odit.\nExpedita reiciendis sed nam quos quia voluptatibus fugiat.",
                            Name = "Johnnie Hansen",
                            Profession = "et",
                            Rate = 80.35299232842074,
                            Rating = 3.7503873248353541
                        },
                        new
                        {
                            Id = 25,
                            Desctiption = "Eos expedita enim nulla magnam a iusto.\nConsequatur distinctio nihil cum alias a.\nVero aut maiores et laborum assumenda quasi tempora aspernatur.",
                            Name = "Lavada Weissnat",
                            Profession = "odit",
                            Rate = 25.298367135645059,
                            Rating = 2.4073261546005149
                        },
                        new
                        {
                            Id = 26,
                            Desctiption = "Sequi ut illo maiores quo ut vero at.\nEius ut provident alias quasi non reiciendis debitis quod.\nMagni aut laborum.",
                            Name = "Terrence Gleason",
                            Profession = "porro",
                            Rate = 46.539925108542633,
                            Rating = 0.557578820994859
                        },
                        new
                        {
                            Id = 27,
                            Desctiption = "Labore qui vel et aperiam enim sit hic ut qui.\nFugit magni et reprehenderit incidunt ut tempora accusantium iure quis.\nOmnis ut quis cupiditate ut voluptatum sed et veniam.\nRecusandae accusamus occaecati architecto neque doloremque delectus et.\nDoloremque voluptates mollitia magni.",
                            Name = "Sasha Stark",
                            Profession = "et",
                            Rate = 60.816835810158793,
                            Rating = 2.1322099734713369
                        },
                        new
                        {
                            Id = 28,
                            Desctiption = "Amet ut optio in.\nVelit magni excepturi qui at placeat ab.\nEnim sit quaerat ut voluptatem et excepturi quaerat tempora.",
                            Name = "Ahmad Wolf",
                            Profession = "maxime",
                            Rate = 65.771438414962702,
                            Rating = 6.2240906368121927
                        },
                        new
                        {
                            Id = 29,
                            Desctiption = "Quibusdam repellat culpa qui beatae et qui.\nQuia atque facere ut.",
                            Name = "Clara Gerlach",
                            Profession = "non",
                            Rate = 115.2571613515062,
                            Rating = 8.4117513934205057
                        },
                        new
                        {
                            Id = 30,
                            Desctiption = "Fugiat porro in nesciunt iste perferendis earum a ut.\nRem quidem similique est delectus recusandae.\nDolorem et dolor assumenda temporibus vitae tempora fugiat ipsam.\nConsequatur nesciunt nulla reiciendis quasi eius voluptatibus.",
                            Name = "Izabella Bernier",
                            Profession = "nisi",
                            Rate = 45.354158144516006,
                            Rating = 8.5891254658760161
                        },
                        new
                        {
                            Id = 31,
                            Desctiption = "Perspiciatis quae id est.\nSit consequuntur corrupti eos corrupti fugit sed a sunt.",
                            Name = "Jovani Simonis",
                            Profession = "qui",
                            Rate = 103.16974525282613,
                            Rating = 0.24938151251961549
                        },
                        new
                        {
                            Id = 32,
                            Desctiption = "Et quas praesentium in.\nOfficia magnam dolores sed sit qui.\nRerum tempora maxime ut in.",
                            Name = "Alvena Nicolas",
                            Profession = "quia",
                            Rate = 50.092919053273704,
                            Rating = 2.3778407100484897
                        },
                        new
                        {
                            Id = 33,
                            Desctiption = "Et quaerat necessitatibus voluptatum adipisci modi excepturi temporibus voluptatibus.\nQuod ut minima.",
                            Name = "Yasmeen Collier",
                            Profession = "atque",
                            Rate = 49.660996254748198,
                            Rating = 0.19417892684888974
                        },
                        new
                        {
                            Id = 34,
                            Desctiption = "Ut recusandae ipsam et ullam quis.\nLaboriosam aut sint consequatur dolor qui deserunt.\nNeque optio omnis earum ipsam molestias ex.\nQuidem atque sed et voluptas.",
                            Name = "Dell Kassulke",
                            Profession = "mollitia",
                            Rate = 107.07176395387937,
                            Rating = 3.5032574150260802
                        },
                        new
                        {
                            Id = 35,
                            Desctiption = "Recusandae rerum accusantium quia et fuga quia nobis et adipisci.\nIn nobis quo voluptatem eveniet aspernatur velit quis a laborum.\nCum vel aspernatur eius enim est error nemo.\nCommodi magnam optio animi numquam tempore animi aperiam est.\nTempore modi dignissimos cupiditate aut.",
                            Name = "Kendrick Lindgren",
                            Profession = "est",
                            Rate = 117.09718428677748,
                            Rating = 4.1742506316743091
                        },
                        new
                        {
                            Id = 36,
                            Desctiption = "Recusandae veniam nostrum ut.\nBeatae nobis ex in sed possimus ex mollitia.\nMaiores aut quae modi.",
                            Name = "Gerda Morissette",
                            Profession = "corporis",
                            Rate = 82.860102076018279,
                            Rating = 5.0857035466868918
                        },
                        new
                        {
                            Id = 37,
                            Desctiption = "Vero nostrum quo et.\nEt quibusdam minima ut voluptatem esse.\nRerum doloremque occaecati ut suscipit.",
                            Name = "Jewell Hodkiewicz",
                            Profession = "animi",
                            Rate = 81.043550541644706,
                            Rating = 9.4014056862338471
                        },
                        new
                        {
                            Id = 38,
                            Desctiption = "Quas aliquam esse consequatur amet provident.\nNisi accusamus aperiam repellendus temporibus.\nCumque non velit a beatae commodi dolorem sunt quibusdam.\nAdipisci voluptatibus doloremque.",
                            Name = "Trace Lueilwitz",
                            Profession = "laudantium",
                            Rate = 25.590062099131785,
                            Rating = 9.2657313026793915
                        },
                        new
                        {
                            Id = 39,
                            Desctiption = "Iusto ratione eius quas autem sunt nihil aut.\nDignissimos voluptates et.\nDolores quidem consequatur ex molestias perferendis error fugiat.\nImpedit sequi modi accusantium sequi ut et a repudiandae.\nAt sequi esse omnis quo eligendi dolorem maiores expedita illum.",
                            Name = "Dexter Pollich",
                            Profession = "iure",
                            Rate = 115.39816681034777,
                            Rating = 1.4217013779197361
                        },
                        new
                        {
                            Id = 40,
                            Desctiption = "Nobis aperiam ducimus consequuntur consequatur et est odio.\nVeniam assumenda itaque.\nReprehenderit fugit provident sit iure in.",
                            Name = "Jettie Hermann",
                            Profession = "consectetur",
                            Rate = 115.08986227032256,
                            Rating = 2.505237782609294
                        },
                        new
                        {
                            Id = 41,
                            Desctiption = "Perferendis voluptas ex sapiente enim est fuga rerum recusandae et.",
                            Name = "Arnold Bode",
                            Profession = "exercitationem",
                            Rate = 84.80617336072315,
                            Rating = 3.3936794816486908
                        },
                        new
                        {
                            Id = 42,
                            Desctiption = "Velit in ab modi nihil iure qui ipsum.",
                            Name = "Jalen Runolfsdottir",
                            Profession = "corrupti",
                            Rate = 52.849376232013739,
                            Rating = 8.073483816382236
                        },
                        new
                        {
                            Id = 43,
                            Desctiption = "Aspernatur praesentium repellendus.\nVitae aut perferendis asperiores enim.",
                            Name = "Kendra Pacocha",
                            Profession = "ducimus",
                            Rate = 72.850427078386033,
                            Rating = 3.9096188470300373
                        },
                        new
                        {
                            Id = 44,
                            Desctiption = "Ad delectus est magnam.\nVoluptatibus nobis deserunt earum provident temporibus nihil aut quia explicabo.\nOmnis aliquid nam doloremque similique non doloremque.\nIn ea id nihil sapiente adipisci facere.\nNam ducimus quia in quod quia ipsum sed est adipisci.",
                            Name = "Petra Koelpin",
                            Profession = "consectetur",
                            Rate = 23.311880584206378,
                            Rating = 2.5232675683327335
                        },
                        new
                        {
                            Id = 45,
                            Desctiption = "Sint rerum porro officia officiis expedita maxime itaque.",
                            Name = "Ettie Lubowitz",
                            Profession = "enim",
                            Rate = 48.223858287941596,
                            Rating = 8.9293162705978926
                        },
                        new
                        {
                            Id = 46,
                            Desctiption = "Dolor accusamus ipsa et repellat sint quibusdam et.\nUnde aliquam quis consectetur.\nIncidunt sunt excepturi animi est quae.\nEaque suscipit autem temporibus molestiae rerum quidem.",
                            Name = "Belle Stark",
                            Profession = "sed",
                            Rate = 41.473675968625429,
                            Rating = 2.6030580385602349
                        },
                        new
                        {
                            Id = 47,
                            Desctiption = "Dignissimos ut labore eos amet sed quia provident ipsa.\nVeniam iste blanditiis officiis omnis voluptatem facilis.\nQui consectetur maxime sed dolore eos sunt.",
                            Name = "Donato Nader",
                            Profession = "debitis",
                            Rate = 69.556733163426031,
                            Rating = 5.6666123567459223
                        },
                        new
                        {
                            Id = 48,
                            Desctiption = "Animi quo temporibus qui enim praesentium sed molestiae ut.\nNostrum quia quas officiis sit voluptas molestias.\nIncidunt reiciendis voluptatibus in accusantium et sit.\nError enim a ab voluptatibus quis.",
                            Name = "Sebastian Crooks",
                            Profession = "nesciunt",
                            Rate = 73.199686697590948,
                            Rating = 6.7027181371593469
                        },
                        new
                        {
                            Id = 49,
                            Desctiption = "Sit repellat distinctio voluptas labore et architecto ex cumque.\nQui est itaque odio omnis qui velit nobis.\nEt saepe saepe tempora delectus ullam occaecati et exercitationem accusantium.\nOdio soluta similique vero quae reiciendis quia natus repellendus distinctio.\nVoluptatem et dolorum natus in quae non fugit expedita facere.",
                            Name = "Shad Kris",
                            Profession = "tenetur",
                            Rate = 93.512542792834594,
                            Rating = 0.84414451888024089
                        },
                        new
                        {
                            Id = 50,
                            Desctiption = "Perspiciatis porro voluptatem omnis sit dolor magnam porro.\nBeatae reprehenderit repellendus.\nRerum eveniet modi vero officiis doloremque.\nEa eveniet voluptatum doloribus sit quis neque.",
                            Name = "Andreane Dooley",
                            Profession = "eos",
                            Rate = 105.22571409578701,
                            Rating = 2.8872157367352469
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
